<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>0x53 | Nameless CTF Platform</title>
        <link rel="icon" href="imgs/icon.png">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Samuel Silva">
        <meta name="creator" content="Samuel Silva">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="css/main.css" type="text/css">
    </head>
    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top">
            <img src="imgs/namelessctfplatform.png" width="210">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ml-auto">
                    <!-- content in right -->
                    <a href="" class="nav-item nav-link active"><i class="fas fa-brain"></i> Desafios</a>
                    <a href="/ranking" class="nav-item nav-link"><i class="fas fa-medal"></i> Ranking Geral</a>
                    <a href="https://0x53.me/" class="nav-item nav-link"><i class="fas fa-book"></i> Writeups</a>
                </div>
            </div>
        </nav>
        <!-- End of Navbar -->
        <!-- Content-->

        <div class="container-fluid mt-5">
            <div class="row">
                <div class="col-md-3">

                    <div class="card card-min mb-3">
                        <div class="card-header">
                            <h5 class="card-title">Ranking (Top 10)</h5>
                        </div>
                        <div class="card-body">
                            <table class="table table-dark table-striped">
                                <thead>
                                    <th scope="col">#</th>
                                    <th scope="col">Nick</th>
                                    <th scope="col">Pontos</th>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th scope="row">1</th>
                                        <td>p4n1c0</td>
                                        <td>0</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">2</th>
                                        <td>0x53</td>
                                        <td>0</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">3</th>
                                        <td>0x53</td>
                                        <td>0</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">4</th>
                                        <td>0x53</td>
                                        <td>0</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">5</th>
                                        <td>0x53</td>
                                        <td>0</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">6</th>
                                        <td>0x53</td>
                                        <td>0</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">7</th>
                                        <td>0x53</td>
                                        <td>0</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">8</th>
                                        <td>0x53</td>
                                        <td>0</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">9</th>
                                        <td>0x53</td>
                                        <td>0</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">10</th>
                                        <td>0x53</td>
                                        <td>0</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>

                <div class="col-md-6">
                    <div class="card card-min mb-3">
                        <div class="card-header">
                            <h5 class="card-title">Desafios</h5>
                        </div>
                        <div class="card-body">
                            
                            <div class="row">
                                <div class="col-md-4 mb-3">
                                    <button class="btn btn-dark"><strong>Find Me</strong><br>50 Pts | WEB | Fácil</button>
                                </div>
                                <div class="col-md-4 mb-3">
                                    <button class="btn btn-dark solved"><strong>CRLF</strong><br>200 Pts | WEB | Médio</button>
                                </div>
                                <div class="col-md-4 mb-3">
                                    <button class="btn btn-dark"><strong>Steal my Cookie</strong><br>200 Pts | WEB | Médio</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="card mb-3">
                        <div class="card-header">
                            <h5 class="card-title">Perfil</h5>
                        </div>
                        <div class="card-body align-middle text-center"> 
                            <img src="imgs/hacker.png">
                            <p class="mt-3 mb-3">0x53</p>
                            <h4 class="mb-5"><strong>Pontuação:</strong> 000</h4>
                            <hr>
                            <p class="mt-4 unfocus"><strong>Oferecido por:</strong> 0x53, P4n1c0 e Grupo Nameless.</p>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <!-- End of Content -->

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">
    </body>
</html>